packages:
    - name: indexer-cron
      functions:
        - name: push
          binary: false
          runtime: python:default
          web: false
          environment:
            VISION_SEARCH_URL: ${VISION_SEARCH_URL}
            INDEXER_SECRET: ${INDEXER_SECRET}
          triggers:
          - name: trigger-daily
            sourceType: scheduler
            sourceDetails:
              cron: "0 7 * * *"
