name: art-museum-vision-search

databases:
  - cluster_name: museum-vision
    db_name: ${DATABASE_NAME}
    db_user: ${DATABASE_USER}
    engine: PG
    name: museum-vision
    production: true
    version: "17"
ingress:
  rules:
    - component:
        name: art-museum-vision-search
      match:
        path:
          prefix: /
region: nyc
services:
  - envs:
      - key: DATABASE_URL
        scope: RUN_TIME
        value: ${museum-vision.DATABASE_URL}
      - key: ART_MUSEUM_COLLECTION_URL
        scope: RUN_TIME
        value: ${ART_MUSEUM_COLLECTION_URL}
      - key: INDEXER_SECRET
        scope: RUN_TIME
        value: ${INDEXER_SECRET}
    health_check:
      failure_threshold: 30
      initial_delay_seconds: 60
      period_seconds: 30
    http_port: 8000
    image:
      digest: ${APP_DIGEST}
      registry: jocmp
      registry_type: GHCR
      repository: art-museum-vision-search
    instance_count: 1
    instance_size_slug: apps-s-1vcpu-2gb
    name: art-museum-vision-search
