name: art-museum-vision-search

databases:
  - cluster_name: db-art-museum-vision-search
    db_name: ${DATABASE_NAME}
    db_user: ${DATABASE_USER}
    engine: PG
    name: db-art-museum-vision-search
    production: true
    version: "17"
envs:
  - key: ART_MUSEUM_COLLECTION_URL
    scope: RUN_TIME
    value: ${ART_MUSEUM_COLLECTION_URL}
ingress:
  rules:
    - component:
        name: jocmp-art-museum-vision-search
      match:
        path:
          prefix: /
region: nyc
services:
  - envs:
      - key: DATABASE_URL
        scope: RUN_TIME
        value: ${db-art-museum-vision-search.DATABASE_URL}
    health_check:
      failure_threshold: 30
      initial_delay_seconds: 60
      period_seconds: 30
    http_port: 8000
    image:
      digest: ${DIGEST}
      registry: jocmp
      registry_type: GHCR
      repository: art-museum-vision-search
    instance_count: 1
    instance_size_slug: apps-s-1vcpu-2gb
    name: jocmp-art-museum-vision-search
