version: "3.8"
services:
  app:
    image: mcr.microsoft.com/devcontainers/python:3.11
    volumes:
      - ..:/workspace:cached
    command: sleep infinity
    network_mode: service:db
    env_file: devcontainer.env
    environment:
      - UV_LINK_MODE=copy
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/museum_vision
      - PYTHONPATH=/app

  db:
    image: pgvector/pgvector:pg15
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
    hostname: postgres
    environment:
      POSTGRES_DB: museum_vision
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - 5432:5432

volumes:
  postgres-data: null
