packages:
    - name: indexer-cron
      environment: {}
      parameters: {}
      functions:
        - name: push
          binary: false
          runtime: python:default
          web: false
          triggers:
          - name: trigger-daily
            sourceType: scheduler
            sourceDetails:
              cron: "* * * * *"
