name: Build, Push and Deploy a Docker Image

on:
  push:
    branches: [main]

permissions:
  contents: read
  packages: write

jobs:
  build-push-app:
    runs-on: ubuntu-latest
    outputs:
      digest: ${{ steps.push.outputs.digest }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Log in to the Container registry
        uses: docker/login-action@v3.3.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push Docker image
        id: push
        uses: docker/build-push-action@v6.5.0
        with:
          context: .
          push: true
          tags: ghcr.io/${{ github.repository }}:latest
  deploy:
    runs-on: ubuntu-latest
    needs: [build-push-app]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Deploy
        uses: digitalocean/app_action/deploy@v2
        env:
          APP_DIGEST: ${{ needs.build-push-app.outputs.digest }}
          ART_MUSEUM_COLLECTION_URL: ${{ secrets.ART_MUSEUM_COLLECTION_URL }}
          DATABASE_USER: ${{ secrets.DATABASE_USER }}
          DATABASE_NAME: ${{ secrets.DATABASE_NAME }}
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
